# Generated by Django 5.2.7 on 2025-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HygieneSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], max_length=20)),
                ('school', models.CharField(max_length=150)),
                ('challenges', models.TextField()),
                ('suggestions', models.TextField(blank=True)),
            ],
        ),
    ]
